<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

<head>
    <title>rPi-Dupe</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="Description" content="Raspberry Pi SD Card Duplicator">

    <style>
#progress_bar {
    width: 0%;
    height: 30px;
    background-color: #1A4384;
    text-align: center;
    line-height: 30px;
    color: #C7CFDB;
}
    </style>
    <!-- Leave style tags here, CherryPy will replace with Skeleton CSS Template Code -->
    <style></style>

</head>

<body>


    <div class="container">
        <div class="sixteen columns osid_icon">
            <h8>Open Source Image Duplicator - Python v1.1.1</h8>
            <hr />
        </div>
        <div class="sixteen columns">
        </div>
